resolver: lts-14.26

packages:
- '.'

# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps:
  - harg-0.4.0.0
  - higgledy-0.3.1.0 # harg dependency
  - ring-buffer-0.4
  - with-utf8-1.0.1.0

# ring-buffer has a tight upper bound on base
allow-newer: true

flags: {}

extra-package-dbs: []
