resolver: lts-16.3

packages:
- '.'

# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps:
  - ring-buffer-0.4
  - with-utf8-1.0.1.0
  - sqlite-simple-0.4.18.0
  - direct-sqlite-2.3.26
  - tz-0.1.3.3
  - aeson-deriving-0.1.1.2

# ring-buffer has a tight upper bound on base
allow-newer: true

flags: {}

extra-package-dbs: []
